// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParkingF.API.Data;

#nullable disable

namespace SmartParkingF.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512170826_AddPaymentsTable")]
    partial class AddPaymentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartParkingF.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarPlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartParkingF.API.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A1",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A2",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A3",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A4",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A5",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A6",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A7",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A8",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A9",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A10",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 11,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A11",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 12,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A12",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 13,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A13",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 14,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A14",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 15,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A15",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 16,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A16",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 17,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A17",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 18,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A18",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 19,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A19",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 20,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A20",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 21,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A21",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 22,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A22",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 23,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A23",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 24,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A24",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 25,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A25",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 26,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A26",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 27,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A27",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 28,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A28",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 29,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A29",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 30,
                            Location = "Ground Floor",
                            PricePerHour = 5.0m,
                            PricePerNight = 50.0m,
                            PropertyId = 1,
                            SpotNumber = "A30",
                            Status = "Available",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 31,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B1",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 32,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B2",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 33,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B3",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 34,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B4",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 35,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B5",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 36,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B6",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 37,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B7",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 38,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B8",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 39,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B9",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 40,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B10",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 41,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B11",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 42,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B12",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 43,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B13",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 44,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B14",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 45,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B15",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 46,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B16",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 47,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B17",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 48,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B18",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 49,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B19",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 50,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B20",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 51,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B21",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 52,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B22",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 53,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B23",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 54,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B24",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 55,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B25",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 56,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B26",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 57,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B27",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 58,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B28",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 59,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B29",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 60,
                            Location = "First Floor",
                            PricePerHour = 10.0m,
                            PricePerNight = 80.0m,
                            PropertyId = 1,
                            SpotNumber = "B30",
                            Status = "Available",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 61,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C1",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 62,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C2",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 63,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C3",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 64,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C4",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 65,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C5",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 66,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C6",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 67,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C7",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 68,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C8",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 69,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C9",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 70,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C10",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 71,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C11",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 72,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C12",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 73,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C13",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 74,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C14",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 75,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C15",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 76,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C16",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 77,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C17",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 78,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C18",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 79,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C19",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 80,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C20",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 81,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C21",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 82,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C22",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 83,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C23",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 84,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C24",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 85,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C25",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 86,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C26",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 87,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C27",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 88,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C28",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 89,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C29",
                            Status = "Available",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 90,
                            Location = "VIP Section",
                            PricePerHour = 15.0m,
                            PricePerNight = 120.0m,
                            PropertyId = 1,
                            SpotNumber = "C30",
                            Status = "Available",
                            Zone = "C"
                        });
                });

            modelBuilder.Entity("SmartParkingF.API.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSmartParking")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSpots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smart Villa with private parking",
                            HasSmartParking = true,
                            ImageUrl = "https://images.unsplash.com/photo-1506521781263-d8422e82f27a",
                            Location = "Beverly Hills, Cairo",
                            Name = "Luxury Modern Villa",
                            Price = 1250.0m,
                            PricePerHour = 150.0m,
                            PricePerNight = 1250.0m,
                            Rating = 4.9000000000000004,
                            Title = "Luxury Modern Villa",
                            TotalSpots = 90
                        });
                });

            modelBuilder.Entity("SmartParkingF.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarPlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SmartParkingF.API.Models.ParkingSpot", b =>
                {
                    b.HasOne("SmartParkingF.API.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SmartParkingF.API.Models.Reservation", b =>
                {
                    b.HasOne("SmartParkingF.API.Models.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartParkingF.API.Models.Property", "Property")
                        .WithMany("Reservations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartParkingF.API.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParkingF.API.Models.Property", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
